### ISSUE TITLE
CWSM Crashes on play

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#88] opened 2024-11-27 05:43 UTC
### Version information

4.2.1

### Reproduction Steps

1. Start game
2. Go into world
3. Crash

### Java version

21

### Crash Report file

https://mclo.gs/D5SMbBL 

### Additional information

I could not find any that would be when you go in the world.

**Comment by BluSpring** [comment] 2024-11-27 06:08
Duplicate of #60.

**Closed as not planned by BluSpring** 2024-11-27 06:08 UTC
Labels: T-crash, status: invalid
