### ISSUE TITLE
Crash with mod "Touhou Little Maid"

### ISSUE THREAD

**Issue by Xiaokang2022** [BluSpring/Kilt#87] opened 2024-11-25 15:32 UTC
### Version information

Kilt-0.0.1+mc1.20.1+build.6bcec6

### Reproduction Steps

1. Put in the relevant mods
2. Run the game
3. Crash...

### Java version

Oracle JDK 23.0.1

### Crash Report file

[latest.log](https://github.com/user-attachments/files/17905162/latest.log)

### Additional information

All mods:

* **Dependencies**:
    * fabric-api-0.92.2+1.20.1
    * fabric-language-kotlin-1.12.3+kotlin.2.0.21
    * sodium-fabric-0.5.11+mc1.20.1
    * architectury-9.2.14-fabric
    * ForgeConfigAPIPort-v8.0.1-1.20.1-Fabric
* **Kilt**:
    * Kilt-0.0.1+mc1.20.1+build.6bcec6
* **Other**:
    * touhoulittlemaid-1.20.1-release-1.1.13

**Comment by BluSpring** [comment] 2024-11-25 15:33
Duplicate of #33.

**Closed as not planned by BluSpring** 2024-11-25 15:33 UTC
Labels: T-crash, status: invalid
