### ISSUE TITLE
Cracker's Wither Storm

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#57] opened 2024-10-27 04:41 UTC
### Version information

4.2.1

### Reproduction Steps

1: Place mod along with Kilt Dependencies
2: Start game
3: Go to Singleplayer
4: Attempt to create world
5: Crash
6: Celebrate

### Java version

22

### Crash Report file

https://mclo.gs/AgSFOra 

### Additional information

GG, this one actually booted.

**Comment by BluSpring** [comment] 2024-10-27 05:30
Duplicate of #51.

**Closed as not planned by BluSpring** 2024-10-27 05:30 UTC
Labels: T-crash, closed: duplicate
